#program to check if a given value is present in a set or not.
nums = {1, 3, 5, 7, 9, 11}
print("Original sets(nums): ",nums,"\n")
print("Test if 6 exists in nums:")
print(6 in nums)
print("Test if 7 exists in nums:")
print(7 in nums)
print("Test if 11 exists in nums:")
print(11 in nums)
print("Test if 0 exists in nums:")
print(0 in nums)
print("\nTest if 6 is not in nums")
print(6 not in nums)
print("Test if 7 is not in nums")
print(7 not in nums)
print("Test if 11 is not in nums")
print(11 not in nums)
print("Test if 0 is not in nums")
print(0 not in nums)
